const els={input:document.querySelector('#chapterInput'),load:document.querySelector('#loadBtn'),status:document.querySelector('#status'),requestActions:document.querySelector('#requestActions'),requestBtn:document.querySelector('#requestBtn'),checkCache:document.querySelector('#checkCacheBtn'),requestHint:document.querySelector('#requestHint'),chapterCard:document.querySelector('#chapterCard'),mangaTitle:document.querySelector('#mangaTitle'),chapterMeta:document.querySelector('#chapterMeta'),reader:document.querySelector('#reader'),template:document.querySelector('#pageTemplate'),downloadTask:document.querySelector('#downloadTaskBtn'),copyTask:document.querySelector('#copyTaskBtn'),translationFile:document.querySelector('#translationFile'),clearTranslation:document.querySelector('#clearTranslationBtn'),exportTranslation:document.querySelector('#exportTranslationBtn')};
const state={chapter:null,translations:new Map(),pendingId:null};
function setStatus(m,t=''){els.status.textContent=m;els.status.className=`status ${t}`.trim()}
function extractChapterId(v){const m=String(v||'').trim().match(/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i);if(!m)throw new Error('Não encontrei um UUID de capítulo válido.');return m[0]}
function requestUrl(id){const title=`MangaBridge: ${id}`;const body=`Preparar capítulo https://mangadex.org/chapter/${id}`;return `https://github.com/zeckofc143-hub/manga-bridge./issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`}
function hideRequest(){els.requestActions.classList.add('hidden');els.requestHint.classList.add('hidden')}
function showRequest(id){state.pendingId=id;localStorage.setItem('mangaBridgePending',id);els.requestBtn.href=requestUrl(id);els.requestActions.classList.remove('hidden');els.requestHint.classList.remove('hidden')}
async function loadChapter(){let id;try{id=extractChapterId(els.input.value)}catch(e){setStatus(e.message,'error');return}els.load.disabled=true;els.chapterCard.classList.add('hidden');els.reader.innerHTML='';state.chapter=null;state.translations.clear();hideRequest();setStatus('Procurando capítulo preparado no GitHub…');try{const r=await fetch(`./data/${id}.json?v=${Date.now()}`,{cache:'no-store'});if(r.status===404){showRequest(id);setStatus('Esse capítulo ainda não foi preparado. Toque em “Preparar pelo GitHub”, envie a issue e depois volte para verificar.','error');return}if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);const chapter=await r.json();if(!chapter?.pages?.length)throw new Error('Cache do capítulo está vazio.');state.chapter=chapter;localStorage.removeItem('mangaBridgePending');state.pendingId=null;renderChapter();setStatus(`Capítulo carregado: ${chapter.pages.length} páginas.`,'ok')}catch(e){console.error(e);setStatus(`Falha ao carregar cache: ${e.message}`,'error')}finally{els.load.disabled=false}}
function renderChapter(){const c=state.chapter;els.mangaTitle.textContent=c.mangaTitle||'Obra sem título';els.chapterMeta.textContent=[c.volume?`Vol. ${c.volume}`:null,c.chapterNumber?`Cap. ${c.chapterNumber}`:'Capítulo sem número',c.chapterTitle||null,c.sourceLanguage?`idioma: ${c.sourceLanguage}`:null,`${c.pages.length} páginas`].filter(Boolean).join(' • ');els.chapterCard.classList.remove('hidden');els.reader.innerHTML='';for(const p of c.pages){const node=els.template.content.cloneNode(true);const card=node.querySelector('.page-card');card.dataset.page=String(p.page);node.querySelector('.page-number').textContent=`Página ${p.page}`;const img=node.querySelector('.page-image');img.src=p.imageUrl;img.alt=`${c.mangaTitle} — página ${p.page}`;img.addEventListener('error',()=>{card.querySelector('.page-state').textContent='imagem indisponível'});els.reader.appendChild(node)}renderTranslations()}
function buildTask(){if(!state.chapter)throw new Error('Carregue um capítulo primeiro.');const c=state.chapter;return{schema:'manga-bridge-task/v1',createdAt:new Date().toISOString(),purpose:'Preparar tradução PT-BR com auxílio do ChatGPT, sem API de IA no site.',chapter:{chapterId:c.chapterId,mangaId:c.mangaId,mangaTitle:c.mangaTitle,volume:c.volume,chapterNumber:c.chapterNumber,chapterTitle:c.chapterTitle,sourceLanguage:c.sourceLanguage,pages:c.pages},requestedOutput:{schema:'manga-bridge-translation/v1',chapterId:c.chapterId,targetLanguage:'pt-BR',translations:[{page:1,text:'Texto traduzido da página 1'}]}}}
function downloadJson(d,n){const b=new Blob([JSON.stringify(d,null,2)],{type:'application/json;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u)}
async function copyTask(){try{await navigator.clipboard.writeText(JSON.stringify(buildTask(),null,2));setStatus('Tarefa copiada.','ok')}catch(e){setStatus(`Não consegui copiar: ${e.message}`,'error')}}
function downloadTask(){try{downloadJson(buildTask(),`manga-bridge-tarefa-${state.chapter.chapterId.slice(0,8)}.json`);setStatus('Tarefa JSON baixada.','ok')}catch(e){setStatus(e.message,'error')}}
function normalizeTranslation(p){if(!state.chapter)throw new Error('Carregue o capítulo primeiro.');if(p.chapterId&&p.chapterId!==state.chapter.chapterId)throw new Error('chapterId diferente do capítulo aberto.');const rows=p.translations||p.pages;if(!Array.isArray(rows))throw new Error('JSON sem array translations.');const m=new Map();for(const r of rows){const page=Number(r?.page??r?.index),text=r?.text??r?.translation??r?.translatedText;if(Number.isInteger(page)&&page>0&&page<=state.chapter.pages.length&&typeof text==='string')m.set(page,text.trim())}if(!m.size)throw new Error('Nenhuma tradução válida.');return m}
function renderTranslations(){document.querySelectorAll('.page-card').forEach(card=>{const p=Number(card.dataset.page),box=card.querySelector('.translation-box'),content=card.querySelector('.translation-content'),label=card.querySelector('.page-state'),text=state.translations.get(p);if(text){content.textContent=text;box.classList.remove('hidden');label.textContent='traduzida'}else{content.textContent='';box.classList.add('hidden');label.textContent='original'}})}
async function importTranslation(f){if(!f)return;try{state.translations=normalizeTranslation(JSON.parse(await f.text()));renderTranslations();setStatus(`${state.translations.size} página(s) traduzida(s).`,'ok')}catch(e){setStatus(`Falha ao importar: ${e.message}`,'error')}finally{els.translationFile.value=''}}
function clearTranslations(){state.translations.clear();renderTranslations();setStatus('Traduções removidas.')}
function exportTranslations(){if(!state.chapter)return setStatus('Carregue um capítulo primeiro.','error');downloadJson({schema:'manga-bridge-translation/v1',chapterId:state.chapter.chapterId,targetLanguage:'pt-BR',translations:[...state.translations.entries()].sort((a,b)=>a[0]-b[0]).map(([page,text])=>({page,text}))},`manga-bridge-traducao-${state.chapter.chapterId.slice(0,8)}.json`);setStatus('Tradução exportada.','ok')}
els.load.addEventListener('click',loadChapter);els.input.addEventListener('keydown',e=>{if(e.key==='Enter')loadChapter()});els.requestBtn.addEventListener('click',()=>{setStatus('Envie a issue no GitHub. Quando voltar, toque em “Verificar novamente”.')});els.checkCache.addEventListener('click',loadChapter);els.downloadTask.addEventListener('click',downloadTask);els.copyTask.addEventListener('click',copyTask);els.translationFile.addEventListener('change',e=>importTranslation(e.target.files?.[0]));els.clearTranslation.addEventListener('click',clearTranslations);els.exportTranslation.addEventListener('click',exportTranslations);
const pending=localStorage.getItem('mangaBridgePending');if(pending){els.input.value=`https://mangadex.org/chapter/${pending}`;showRequest(pending)}
window.addEventListener('focus',()=>{if(localStorage.getItem('mangaBridgePending'))loadChapter()});
