(function(root,factory){
  if(typeof module==='object'&&module.exports) module.exports=factory(require('./translator-core.js'));
  else root.DeseraTranslator=factory(root.DeseraTranslator);
})(typeof globalThis!=='undefined'?globalThis:this,function(T){
  'use strict';
  if(!T) throw new Error('translator-core.js precisa carregar antes de grammar-v12.js');

  const W=[
    ['coisa','dera','noun'],['ver','nera','verb'],['ir','vela','verb'],['falar','sena','verb'],['casa','sorin','noun'],['lugar','navi','noun'],['água','mela','noun'],['bom','fera','adj'],['fazer','kora','verb'],['pessoa','mi','noun'],
    ['agora','nora','time'],['ontem','doru','time'],['amanhã','wena','time'],['hoje','nori','time'],['antes','dorel','time'],['depois','wenal','time'],['liberdade','savar','noun'],['magia','haren','noun'],['mundo','mora','noun'],['universo','orai','noun'],
    ['vida','vira','noun'],['morte','moren','noun'],['corpo','dema','noun'],['mente','selar','noun'],['alma','oran','noun'],['amigo','savi','noun'],['livro','tiren','noun'],['escola','kalen','noun'],['caminho','rava','noun'],['nome','nema','noun'],
    ['origem','vora','noun'],['fim','sora','noun'],['começo','kava','noun'],['tempo','temir','noun'],['espaço','savel','noun'],['fogo','fara','noun'],['terra','tora','noun'],['vento','vesa','noun'],['luz','luma','noun'],['escuro','nokal','adj'],
    ['som','sona','noun'],['silêncio','hesar','noun'],['entender','toler','verb'],['gostar','dusar','verb'],['saber','seru','verb'],['conhecer','keren','verb'],['pensar','mena','verb'],['sentir','sira','verb'],['aprender','velin','verb'],['usar','fira','verb'],
    ['ler','lera','verb'],['escrever','krita','verb'],['criar','kiren','verb'],['dormir','doma','verb'],['acordar','kara','verb'],['correr','rali','verb'],['andar','vani','verb'],['lembrar','neraia','verb'],['esquecer','shera','verb'],['ter','darin','verb'],
    ['grande','gara','adj'],['pequeno','mira','adj'],['bonito','lira','adj'],['feio','doku','adj'],['novo','nela','adj'],['velho','dora','adj'],['forte','karel','adj'],['fraco','senu','adj'],['rápido','tavi','adj'],['lento','moru','adj'],['certo','kera','adj'],['errado','zora','adj'],
    ['aqui','javi','loc'],['aí','wevi','loc'],['lá','xavi','loc'],['quem','shi','interrogative'],['o que','kai','interrogative'],['onde','davi','interrogative'],['como','sai','interrogative'],['por que','vori','interrogative'],['qual','kei','interrogative'],
    ['e','ya','connector'],['mas','ru','connector'],['porque','vorae','connector'],['porra','gewes','interjection'],['sim','sei','particle']
  ];
  const work=new Map(), revWork=new Map();
  for(const [pt,de,pos] of W){work.set(T.normalize(pt),{pt,simple:de,pos,status:'working'});revWork.set(de,{pt,pos,status:'working'});}
  const canonFind=T.findExact, canonReverse=T.findExactReverse;
  const pron={eu:'ne',tu:'va','você':'va',voce:'va',ele:'lo',ela:'lo','nós':'nelu',nos:'nelu','vocês':'valu',voces:'valu',eles:'lolu',elas:'lolu'};
  const rpron={ne:'eu',va:'você',lo:'ele',nelu:'nós',valu:'vocês',lolu:'eles'};
  const demo={este:'je',esta:'je',isto:'je',esse:'we',essa:'we',isso:'we',aquele:'xo',aquela:'xo',aquilo:'xo'};
  const rdemo={je:'este',we:'esse',xo:'aquele'};
  const rel={local:'di',origin:'vo',destination:'wa',instrument:'fi',association:'le'};
  const asp={initial:'re',continuous:'li',complete:'na',interrupted:'se',recurrent:'mu'};
  const gram={pronouns:pron,reversePronouns:rpron,demonstratives:demo,reverseDemonstratives:rdemo,relation:rel,aspect:asp,question:'sa',negative:'no',plural:'lu'};
  const time={agora:'nora',hoje:'nori',ontem:'doru','amanhã':'wena',amanha:'wena',antes:'dorel',depois:'wenal'};
  const rtime=Object.fromEntries(Object.entries(time).map(([a,b])=>[b,a]));
  const names=new Set(['zeo','neru','desera','zeck']);
  const articles=new Set(['o','a','os','as','um','uma','uns','umas']);
  const aliases={vc:'você',ce:'você','cê':'você',ta:'está','tá':'está',to:'estou','tô':'estou',pra:'para',pro:'para',pros:'para',pras:'para',num:'em um',numa:'em uma',no:'em o',na:'em a',nos:'em os',nas:'em as',do:'de o',da:'de a',dos:'de os',das:'de as',minha:'meu',minhas:'meus'};
  const adjective=new Set(['bom','boa','bons','boas','grande','grandes','pequeno','pequena','pequenos','pequenas','bonito','bonita','bonitos','bonitas','feio','feia','feios','feias','novo','nova','novos','novas','velho','velha','velhos','velhas','forte','fortes','fraco','fraca','fracos','fracas','rápido','rapido','rápida','rapida','lento','lenta','certo','certa','errado','errada','escuro','escura']);
  const adjLemma={boa:'bom',bons:'bom',boas:'bom',grandes:'grande',pequena:'pequeno',pequenos:'pequeno',pequenas:'pequeno',bonita:'bonito',bonitos:'bonito',bonitas:'bonito',feia:'feio',feios:'feio',feias:'feio',nova:'novo',novos:'novo',novas:'novo',velha:'velho',velhos:'velho',velhas:'velho',fortes:'forte',fraca:'fraco',fracos:'fraco',fracas:'fraco','rápida':'rápido',rapida:'rápido',lenta:'lento',certa:'certo',errada:'errado',escura:'escuro'};
  const singular={coisas:'coisa',casas:'casa',pessoas:'pessoa',amigos:'amigo',livros:'livro',escolas:'escola',caminhos:'caminho',lugares:'lugar',mundos:'mundo',universos:'universo',nomes:'nome'};

  const vf={};
  function add(lemma,forms){for(const [f,a,t] of forms)vf[T.normalize(f)]={lemma,aspect:a||null,time:t||null};}
  add('ver',[['ver'],['vejo'],['vê'],['ve'],['vemos'],['veem'],['vendo','continuous'],['vi','complete','past'],['viu','complete','past'],['viram','complete','past']]);
  add('ir',[['ir'],['vou'],['vai'],['vamos'],['vão'],['vao'],['indo','continuous'],['fui','complete','past'],['foi','complete','past'],['foram','complete','past']]);
  add('falar',[['falar'],['falo'],['fala'],['falamos'],['falam'],['falando','continuous'],['falei','complete','past'],['falou','complete','past']]);
  add('entender',[['entender'],['entendo'],['entende'],['entendemos'],['entendem'],['entendendo','continuous'],['entendi','complete','past'],['entendeu','complete','past']]);
  add('gostar',[['gostar'],['gosto'],['gosta'],['gostamos'],['gostam'],['gostando','continuous'],['gostei','complete','past'],['gostou','complete','past']]);
  add('querer',[['querer'],['quero'],['quer'],['queremos'],['querem'],['querendo','continuous'],['quis','complete','past']]);
  add('permanecer',[['permanecer'],['permaneço'],['permanece'],['permanecem'],['permanecendo','continuous'],['permaneceu','complete','past']]);
  for(const l of ['fazer','criar','saber','conhecer','pensar','sentir','aprender','usar','ler','escrever','dormir','acordar','correr','andar','lembrar','esquecer','ter'])add(l,[[l]]);
  Object.assign(vf,{faco:{lemma:'fazer'},'faço':{lemma:'fazer'},faz:{lemma:'fazer'},fazendo:{lemma:'fazer',aspect:'continuous'},fez:{lemma:'fazer',aspect:'complete',time:'past'},cria:{lemma:'criar'},criando:{lemma:'criar',aspect:'continuous'},criou:{lemma:'criar',aspect:'complete',time:'past'},sabe:{lemma:'saber'},sei:{lemma:'saber'},conhece:{lemma:'conhecer'},pensa:{lemma:'pensar'},penso:{lemma:'pensar'},pensando:{lemma:'pensar',aspect:'continuous'},sente:{lemma:'sentir'},sinto:{lemma:'sentir'},sentindo:{lemma:'sentir',aspect:'continuous'},aprende:{lemma:'aprender'},usa:{lemma:'usar'},uso:{lemma:'usar'},lê:{lemma:'ler'},le:{lemma:'ler'},leio:{lemma:'ler'},lendo:{lemma:'ler',aspect:'continuous'},escreve:{lemma:'escrever'},escrevo:{lemma:'escrever'},escrevendo:{lemma:'escrever',aspect:'continuous'},dorme:{lemma:'dormir'},durmo:{lemma:'dormir'},dormindo:{lemma:'dormir',aspect:'continuous'},acorda:{lemma:'acordar'},acordo:{lemma:'acordar'},corre:{lemma:'correr'},corro:{lemma:'correr'},anda:{lemma:'andar'},ando:{lemma:'andar'},lembra:{lemma:'lembrar'},lembro:{lemma:'lembrar'},esquece:{lemma:'esquecer'},tenho:{lemma:'ter'},tem:{lemma:'ter'}});

  function n(t){return T.normalize(String(t||'').replace(/_/g,' '));}
  function expand(text){let s=' '+String(text||'').trim()+' ';s=s.replace(/\bpor\s+que\b/gi,'por_que').replace(/\bo\s+que\b/gi,'o_que');for(const [a,b] of Object.entries(aliases))s=s.replace(new RegExp('\\b'+a+'\\b','gi'),b);return s.trim();}
  function toks(text){return expand(text).match(/[A-Za-zÀ-ÖØ-öø-ÿÇç_]+|[0-9]+|[^\sA-Za-zÀ-ÖØ-öø-ÿÇç_0-9]/g)||[];}
  function punct(t){return /^[!?.,;:]+$/.test(t);}
  function cop(t){const s=String(t||'').toLowerCase();return ['é','sou','somos','são','sao','era','eram','foi','foram','estou','está','estão','estamos','estao','estava','estavam'].includes(s);}
  function exact(pt){return canonFind(pt)||work.get(T.normalize(pt))||null;}
  const canonicalPos={destino:'noun','presença mental':'noun','presença':'noun','atenção':'noun','despertar':'verb','consciência':'noun','memória':'noun','querer':'verb','vontade':'noun','permanecer':'verb','identidade':'noun'};
  function exactRev(de){const c=canonReverse(de);if(c){const pt=typeof c==='string'?c:c.pt;return {pt,pos:canonicalPos[pt]||'word',status:'canon'};}return revWork.get(String(de||'').toLowerCase())||null;}
  function lx(word,pos){const x=n(word);if(pron[x])return {form:pron[x],pos:'pronoun',lemma:x};if(demo[x])return {form:demo[x],pos:'demonstrative',lemma:x};if(time[x])return {form:time[x],pos:'time',lemma:x};const e=exact(x);if(e)return {form:e.simple,pos:e.pos||pos||'word',lemma:e.pt,status:e.status};if(names.has(x))return {form:x[0].toUpperCase()+x.slice(1),pos:'name',lemma:x};return {form:T.encodeAlphabetWord(x),pos:pos||'word',lemma:x,status:'fallback'};}
  function adj(w){return adjLemma[n(w)]||n(w);}
  function sing(w){const x=n(w);if(singular[x])return {lemma:singular[x],plural:true};if(x.endsWith('s')&&x.length>4&&!x.endsWith('ss'))return {lemma:x.slice(0,-1),plural:true};return {lemma:x,plural:false};}
  function np(raw,relation){let ts=raw.map(n).filter(Boolean).filter(x=>!articles.has(x));if(!ts.length)return null;let poss=null;if(['meu','meus'].includes(ts[0])){poss='nele';ts=ts.slice(1);}else if(['seu','seus'].includes(ts[0])){poss='vale';ts=ts.slice(1);}let dem=null;if(demo[ts[0]]){dem=demo[ts[0]];ts=ts.slice(1);}if(!ts.length)return {form:poss||dem||''};let pl=false,A=[],N=[];for(const x of ts){if(adjective.has(x))A.push(lx(adj(x),'adj').form);else{const s=sing(x);pl=pl||s.plural;N.push(lx(s.lemma,'noun').form);}}let core=[dem,...A,...N].filter(Boolean).join(' ');let parts=core.split(' ');if(pl)parts[parts.length-1]+=gram.plural;if(relation)parts[parts.length-1]+=rel[relation];return {form:[poss,parts.join(' ')].filter(Boolean).join(' ')};}
  function detect(tokens){for(let i=0;i<tokens.length;i++){if(cop(tokens[i])){if(i+1<tokens.length&&vf[n(tokens[i+1])]?.aspect==='continuous')return {index:i+1,aux:i,info:{...vf[n(tokens[i+1])],aspect:'continuous'}};continue;}if(vf[n(tokens[i])])return {index:i,aux:null,info:{...vf[n(tokens[i])]}};}return null;}
  function groups(tokens){const a=[];let cur=[];for(const t of tokens){const s=String(t).toLowerCase();if((s==='e'||s==='mas')&&cur.length){a.push({tokens:cur,connector:s});cur=[];}else cur.push(t);}a.push({tokens:cur,connector:null});return a;}

  function clause(input,p=''){
    let z=input.filter(x=>!punct(x));if(!z.length)return '';let q=p.includes('?'),neg=false;z=z.filter(x=>{if(['não','nao'].includes(n(x))){neg=true;return false;}return true;});let lead=[];
    const im={'quem':'shi','o que':'kai','onde':'davi','como':'sai','por que':'vori','qual':'kei'};if(z.length&&im[n(z[0])]){lead.push(im[n(z[0])]);z=z.slice(1);q=true;}
    for(let i=0;i<z.length;i++)if(time[n(z[i])]){lead.unshift(time[n(z[i])]);z.splice(i,1);break;}
    const ci=z.findIndex(cop), d=detect(z);
    if(ci>=0&&(!d||d.aux===null)){const left=z.slice(0,ci),right=z.slice(ci+1),sub=np(left),pred=right.length===1&&adjective.has(n(right[0]))?lx(adj(right[0]),'adj').form:(np(right)?.form||'');let out;if(lead.includes('davi'))out=[sub?.form,'davidi'].filter(Boolean).join(' ');else if(lead.includes('shi'))out=[sub?.form,'shi'].filter(Boolean).join(' ');else if(lead.includes('kai'))out=[sub?.form,'kai'].filter(Boolean).join(' ');else out=[...lead,sub?.form,pred].filter(Boolean).join(' ');if(neg)out+=gram.negative;if(q)out+=gram.question;return out;}
    if(!d){let out=[...lead,np(z)?.form].filter(Boolean).join(' ');if(neg)out+=gram.negative;if(q)out+=gram.question;return out;}
    let aspect=d.info.aspect||null;if(d.info.time==='past'&&!lead.includes('doru'))lead.unshift('doru');let before=z.slice(0,d.index),after=z.slice(d.index+1);if(d.aux!==null)before=z.slice(0,d.aux);
    if(d.info.lemma==='ir'&&after.length&&vf[n(after[0])]&&n(z[d.index])!=='indo'&&n(z[d.index])!=='ir'){if(!lead.includes('wena'))lead.unshift('wena');d.info=vf[n(after[0])];after=after.slice(1);aspect=d.info.aspect||null;}
    let subject=null,pi=before.findIndex(x=>pron[n(x)]);if(pi>=0){subject=pron[n(before[pi])];before.splice(pi,1);}else if(before.length&&!['quem','o que','onde','como','por que','qual'].includes(n(before[0]))){subject=np(before)?.form;before=[];}
    let objLead=null;if(lead.length&&['shi','kai'].includes(lead[lead.length-1])&&subject)objLead=lead.pop();let qual=false;if(lead.includes('kei')){lead=lead.filter(x=>x!=='kei');qual=true;}
    const obj=[],rels=[];function consume(seq){let i=0;while(i<seq.length){const x=n(seq[i]);if(articles.has(x)){i++;continue;}if(['em','para','de','com'].includes(x)){let j=i+1,g=[];while(j<seq.length&&!['em','para','de','com'].includes(n(seq[j]))){g.push(seq[j]);j++;}if(x==='de'&&['gostar','lembrar','esquecer','falar','saber','entender'].includes(d.info.lemma)){obj.push(...g);i=j;continue;}let r=x==='em'?'local':x==='para'?'destination':x==='de'?(d.info.lemma==='ir'?'origin':'association'):(g.length===1&&['mim','me','você','voce','ele','ela','amigo','pessoa'].includes(n(g[0]))?'association':'instrument');const a=np(g,r);if(a)rels.push(a.form);i=j;continue;}obj.push(seq[i]);i++;}}
    consume(before);consume(after);let object=objLead||(obj.length?np(obj)?.form:null);if(qual&&object)object='kei '+object;let v=lx(d.info.lemma,'verb').form;if(aspect)v+=asp[aspect];if(neg)v+=gram.negative;if(q)v+=gram.question;return [...lead,subject,object,...rels,v].filter(Boolean).join(' ');
  }

  function translateSentence(text){const raw=String(text||'').trim(),p=(raw.match(/[!?]+$/)||[''])[0],body=raw.replace(/[!?]+$/,'').trim(),ex=expand(body);const sub=ex.match(/^(eu|você|voce|tu|ele|ela|nós|nos|vocês|voces|eles|elas)\s+(entendo|entende|entendemos|entendem)\s+o_que\s+(eu|você|voce|tu|ele|ela|nós|nos|vocês|voces|eles|elas)\s+(estou|está|estamos|estão|estao)\s+([A-Za-zÀ-ÖØ-öø-ÿÇç]+ndo)$/i);if(sub){const s1=pron[T.normalize(sub[1])],s2=pron[T.normalize(sub[3])],m=vf[T.normalize(sub[2])]||{lemma:'entender'},e=vf[T.normalize(sub[5])]||{lemma:T.normalize(sub[5])};return [s1,s2,lx(e.lemma,'verb').form+asp.continuous,'kai',lx(m.lemma,'verb').form+(p.includes('?')?gram.question:'')].join(' ');}const gs=groups(toks(body)),out=[];for(let i=0;i<gs.length;i++){out.push(clause(gs[i].tokens,i===gs.length-1?p:''));if(gs[i].connector)out.push(lx(gs[i].connector,'connector').form);}return out.filter(Boolean).join(' ')+(p.includes('!')?'!':'');}
  function translate(text){const raw=String(text||'');if(!raw.trim())return {output:'',status:'empty',items:[]};const direct=canonFind(raw.trim());if(direct)return {output:direct.simple,status:direct.status,items:[direct],canonical:direct.status==='canon',direct:true};const parts=raw.match(/[^.!?]+[.!?]*|[.!?]+/g)||[raw];const output=parts.map(s=>{const m=s.match(/^(.*?)([.!?]+)?$/s),b=(m?.[1]||'').trim(),p=m?.[2]||'';if(!b)return p;let r=translateSentence(b+p);if(p.includes('.')&&!r.endsWith('.'))r+='.';return r;}).join(' ').replace(/\s+([,.!?])/g,'$1').replace(/\s{2,}/g,' ').trim();return {output,status:'grammar',items:[],canonical:false,direct:false,grammar:true};}

  const suffixes=[['question','sa'],['negative','no'],['aspect','li'],['aspect','re'],['aspect','na'],['aspect','se'],['aspect','mu'],['relation','di'],['relation','vo'],['relation','wa'],['relation','fi'],['relation','le'],['plural','lu']];
  function morph(w){const raw=String(w||'').toLowerCase();if(rtime[raw])return {root:raw,time:rtime[raw],suffixes:[]};const d=exactRev(raw);if(d)return {root:raw,entry:d,decoded:d.pt,suffixes:[]};if(rpron[raw])return {root:raw,pronoun:rpron[raw],decoded:rpron[raw],suffixes:[]};if(rdemo[raw])return {root:raw,demonstrative:rdemo[raw],suffixes:[]};function base(x){const e=exactRev(x);if(e)return {root:x,entry:e,decoded:e.pt};if(rpron[x])return {root:x,pronoun:rpron[x],decoded:rpron[x]};const dec=T.decodeAlphabetWord(x);if(dec)return {root:x,decoded:dec};return null;}function walk(x,k){const b=base(x);if(b)return {...b,suffixes:[]};if(k>3)return null;for(const [type,suf] of suffixes)if(x.length>suf.length+1&&x.endsWith(suf)){const i=walk(x.slice(0,-suf.length),k+1);if(i)return {...i,suffixes:[...i.suffixes,{type,value:suf}]};}return null;}return walk(raw,0)||{root:raw,decoded:T.legacyReverse?.[raw]||raw,suffixes:[]};}
  function ger(l){if(l.endsWith('ar'))return l.slice(0,-2)+'ando';if(l.endsWith('er'))return l.slice(0,-2)+'endo';if(l.endsWith('ir'))return l.slice(0,-2)+'indo';return l+'ndo';}
  function present(l,s){const irr={ver:['vejo','vê','vemos','veem'],ir:['vou','vai','vamos','vão'],querer:['quero','quer','queremos','querem'],fazer:['faço','faz','fazemos','fazem'],ter:['tenho','tem','temos','têm'],saber:['sei','sabe','sabemos','sabem'],permanecer:['permaneço','permanece','permanecemos','permanecem'],ler:['leio','lê','lemos','leem'],falar:['falo','fala','falamos','falam'],entender:['entendo','entende','entendemos','entendem'],gostar:['gosto','gosta','gostamos','gostam']};const ix=s==='eu'?0:s==='nós'?2:['eles','elas','vocês'].includes(s)?3:1;if(irr[l])return irr[l][ix];if(l.endsWith('ar'))return l.slice(0,-2)+(ix===0?'o':ix===2?'amos':ix===3?'am':'a');if(l.endsWith('er'))return l.slice(0,-2)+(ix===0?'o':ix===2?'emos':ix===3?'em':'e');if(l.endsWith('ir'))return l.slice(0,-2)+(ix===0?'o':ix===2?'imos':ix===3?'em':'e');return l;}
  function past(l){const x={ver:'vi',ir:'fui',fazer:'fiz',ter:'tive',saber:'soube',querer:'quis'};return x[l]||(l.endsWith('ar')?l.slice(0,-2)+'ei':(l.endsWith('er')||l.endsWith('ir'))?l.slice(0,-2)+'i':l);}
  function fem(n){return ['casa','memória','magia','vida','morte','água','terra','liberdade','identidade','presença','consciência'].includes(n);}
  function adjPt(a,n){const m={bom:'boa',bonito:'bonita',feio:'feia',novo:'nova',velho:'velha',fraco:'fraca',rápido:'rápida',lento:'lenta',certo:'certa',errado:'errada',escuro:'escura'};return fem(n)?(m[a]||a):a;}
  function demoPt(d,n){return fem(n)?({este:'esta',esse:'essa',aquele:'aquela'}[d]||d):d;}

  function reverseClause(text){let q=/\?$/.test(text),clean=text.replace(/[!?.,;:]+$/,'').trim();if(!clean)return '';let ws=clean.split(/\s+/);if(ws.length===5&&rpron[ws[0]]&&rpron[ws[1]]&&ws[3]==='kai'){const e=morph(ws[2]),m=morph(ws[4]),ml=m.entry?.pt||m.decoded,el=e.entry?.pt||e.decoded,ms=rpron[ws[0]],es=rpron[ws[1]],cont=e.suffixes.some(x=>x.type==='aspect'&&x.value==='li'),qq=m.suffixes.some(x=>x.type==='question');let out=ms+' '+present(ml,ms)+' o que '+es+' '+(cont?(es==='eu'?'estou':es==='nós'?'estamos':['eles','elas','vocês'].includes(es)?'estão':'está')+' '+ger(el):present(el,es));return out+((qq||q)?'?':'');}
    const ci=ws.findIndex(w=>w==='ya'||w==='ru');if(ci>0){const left=ws.slice(0,ci).join(' '),right=ws.slice(ci+1).join(' '),first=left.split(/\s+/)[0],right2=(rpron[first]&&!rpron[right.split(/\s+/)[0]])?first+' '+right:right;return reverseClause(left)+' '+(ws[ci]==='ya'?'e':'mas')+' '+reverseClause(right2)+(q?'?':'');}
    let tm=null,sub=null,verb=null,obj=[],rels=[],lead=[],pending=null;for(const w of ws){const p=morph(w);if(p.time){tm=p.time;continue;}if(['shi','kai','davi','sai','vori','kei'].includes(w)){lead.push({shi:'quem',kai:'o que',davi:'onde',sai:'como',vori:'por que',kei:'qual'}[w]);continue;}const sf=Object.fromEntries(p.suffixes.map(x=>[x.type,x.value])),lemma=p.entry?.pt||p.decoded||p.pronoun||w,pos=p.entry?.pos;if(p.demonstrative){pending=p.demonstrative;continue;}if(sf.question)q=true;if(pos==='verb'||vf[T.normalize(lemma)]){verb={lemma,aspect:sf.aspect,negative:Boolean(sf.negative)};continue;}if(p.pronoun&&!sub&&!sf.relation){sub=p.pronoun;continue;}if(sf.relation){rels.push({lemma,rel:sf.relation,plural:Boolean(sf.plural),pronoun:p.pronoun});continue;}obj.push({lemma,plural:Boolean(sf.plural),demonstrative:pending,pos});pending=null;}
    if(!verb){const loc=rels.find(r=>r.rel==='di'&&r.lemma==='onde');if(loc&&sub)return 'onde '+sub+' está'+(q?'?':'');const poss=rels.find(r=>r.rel==='le'&&r.pronoun),ns=obj.filter(o=>o.pos==='noun'||!o.pos),as=obj.filter(o=>o.pos==='adj');if(poss&&ns.length){let s=(poss.pronoun==='eu'?(fem(ns[0].lemma)?'minha':'meu'):'seu')+' '+ns[0].lemma;if(as.length)s+=' é '+as.map(o=>adjPt(o.lemma,ns[0].lemma)).join(' ');return s+(q?'?':'');}if(obj.length>=2&&as.length){const ns2=obj.filter(o=>o.pos!=='adj'),first=ns2.map(o=>(o.demonstrative?demoPt(o.demonstrative,o.lemma)+' ':'')+o.lemma).join(' '),quality=as.map(o=>adjPt(o.lemma,ns2[0]?.lemma)).join(' ');return [sub,first].filter(Boolean).join(' ')+' é '+quality+(q?'?':'');}let s=[...lead,sub,...obj.map(o=>(o.demonstrative?demoPt(o.demonstrative,o.lemma)+' ':'')+o.lemma),...rels.map(r=>r.lemma)].filter(Boolean).join(' ');return s+(q?'?':'');}
    let poss=rels.find(r=>r.rel==='le'&&r.pronoun&&!sub);if(poss&&obj.length){const o=obj.shift();sub=(poss.pronoun==='eu'?(fem(o.lemma)?'minha':'meu'):'seu')+' '+o.lemma;rels=rels.filter(r=>r!==poss);}if(!sub&&obj.length>1)sub=obj.shift().lemma;let vw=verb.aspect==='li'?(sub==='eu'?'estou':sub==='nós'?'estamos':['eles','elas','vocês'].includes(sub)?'estão':'está')+' '+ger(verb.lemma):verb.aspect==='na'?past(verb.lemma):verb.aspect==='re'?'começa a '+verb.lemma:verb.aspect==='se'?'parou de '+verb.lemma:verb.aspect==='mu'?'costuma '+verb.lemma:present(verb.lemma,['eu','você','ele','ela','nós','vocês','eles','elas'].includes(sub)?sub:'ele');if(verb.negative)vw='não '+vw;let ot=obj.map(o=>(o.demonstrative?demoPt(o.demonstrative,o.lemma)+' ':'')+o.lemma+(o.plural?'s':'')).join(' ');if(['gostar','lembrar','esquecer'].includes(verb.lemma)&&ot)ot='de '+ot;const rt=rels.map(r=>({di:'em',vo:'de',wa:'para',fi:'com',le:'de'}[r.rel]||'')+' '+r.lemma).join(' ');let core;if(lead.includes('qual')&&ot){core='qual '+ot+' '+[sub,vw].filter(Boolean).join(' ');lead=lead.filter(x=>x!=='qual');}else core=[sub,vw,ot,rt].filter(Boolean).join(' ');let s=[tm,...lead,core].filter(Boolean).join(' ').replace(/\s+/g,' ').trim();return s+(q?'?':'');}
  function reverse(text){const raw=String(text||'');if(!raw.trim())return {output:'',status:'empty',items:[],unknown:[]};const d=canonReverse(raw.trim());if(d){const pt=typeof d==='string'?d:d.pt;return {output:pt,status:'lexicon',items:[d],unknown:[],direct:true};}if(raw.trim()==='sezhel tolrodu yavas gewes???')return {output:'ta entendendo agora porra???',status:'legacy',items:[],unknown:[]};if(raw.trim()==='sezhel rorrun tolrodu yavas taspen gisner?')return {output:'ta me entendendo agora seu cornudo?',status:'legacy',items:[],unknown:[]};const parts=raw.match(/[^.!?]+[.!?]*|[.!?]+/g)||[raw];const output=parts.map(p=>{const pu=(p.match(/[.!?]+$/)||[''])[0],b=p.replace(/[.!?]+$/,'').trim();if(!b)return pu;let r=reverseClause(b+(pu.includes('?')?'?':''));if(pu.includes('.')&&!r.endsWith('.'))r+='.';if(pu.includes('!')&&!r.endsWith('!'))r+='!';return r;}).join(' ').replace(/\s+([.!?])/g,'$1').trim();return {output,status:'grammar-reverse',items:[],unknown:[]};}

  T.workingEntries=W.map(([pt,simple,pos])=>({pt,simple,pos,status:'working'}));
  T.grammar=gram;T.findWorking=pt=>work.get(T.normalize(pt))||null;T.translateSentence=translateSentence;T.translate=translate;T.reverseClause=reverseClause;T.reverse=reverse;T.parseMorph=morph;
  return T;
});